INSERT INTO QuizQuestions (question_text, options) VALUES
('What describes your ideal Friday night?', '["Netflix and chill at home", "Going out to a party or club", "Dinner at a nice restaurant", "Outdoor adventure or activity"]'),
('How do you handle conflict in relationships?', '["Talk it through immediately", "Need time to think first", "Avoid confrontation", "Seek compromise together"]'),
('What matters most to you in a partner?', '["Sense of humor", "Emotional intelligence", "Ambition and goals", "Physical attraction"]'),
('Your communication style is...', '["Direct and honest", "Gentle and considerate", "Playful and teasing", "Deep and meaningful"]'),
('How do you show love?', '["Words of affirmation", "Quality time together", "Physical touch", "Acts of service"]'),
('Your ideal vacation would be...', '["Beach resort relaxation", "City exploration and museums", "Mountain hiking adventure", "Cultural immersion abroad"]'),
('When it comes to fitness...', '["Gym regular and health focused", "Casual exercise and walks", "Sports and team activities", "Not really my thing"]'),
('Your relationship with social media is...', '["Very active and sharing", "Casual browsing and liking", "Minimal use, prefer privacy", "Completely offline"]'),
('Food preferences:', '["Love trying new cuisines", "Stick to familiar favorites", "Cooking enthusiast", "Dining out preferred"]'),
('Your work-life balance is...', '["Work hard, play hard", "Balanced approach", "Life comes first", "Career is top priority"]'),
('In 5 years you see yourself...', '["Married with children", "Established in career", "Traveling the world", "Living your best life"]'),
('Your stance on marriage is...', '["Definitely want to get married", "Open to it with right person", "Not sure about marriage", "Prefer long-term commitment"]'),
('When it comes to having kids...', '["Definitely want children", "Maybe in the future", "Prefer not to have kids", "Love kids but undecided"]'),
('Your financial approach is...', '["Save and invest for future", "Live in the moment", "Balanced spending and saving", "Money is just a tool"]'),
('Personal growth means...', '["Constant learning and improvement", "Finding inner peace", "Achieving life goals", "Building meaningful relationships"]'),
('Your superpower would be...', '["Reading minds", "Time travel", "Invisibility", "Flying"]'),
('Coffee or tea?', '["Coffee addict", "Tea lover", "Both depending on mood", "Neither, other drinks"]'),
('Your music taste is...', '["Current hits and pop", "Classic rock and oldies", "Electronic and dance", "Diverse across genres"]'),
('Pets in your life...', '["Dog person through and through", "Cat lover definitely", "Love all animals", "Not really into pets"]'),
('Your sense of humor is...', '["Witty and sarcastic", "Goofy and playful", "Dry and clever", "Sweet and wholesome"]'),
('In disagreements, you...', '["Stand your ground firmly", "Seek understanding first", "Find middle ground", "Let it go easily"]'),
('Your social energy is...', '["Life of the party", "Enjoy small groups", "One-on-one conversations", "Happy staying in"]'),
('When planning dates, you prefer...', '["Spontaneous adventures", "Well-planned activities", "Simple and low-key", "Let partner decide"]'),
('Your emotional expression is...', '["Open book, share everything", "Selective but honest", "Private but caring", "Actions speak louder"]'),
('Deal breakers for you include...', '["Dishonesty and lies", "Lack of ambition", "Poor communication", "Different life goals"]');